[package]
name = "foo"
version = "0.1.0"
authors = ["Jack Moffitt <metajack@fb.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
